### ISSUE TITLE
Unable to Add Indicators

### ISSUE THREAD

**Issue by fhightower** [blockadeio/cloud_node#18]
I get the following output when trying to post to the `admin/add-indicators` branch using the format described [here](https://github.com/blockadeio/cloud_node/wiki/Endpoints#post-optional-database-nameadminadd-indicators):

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

The `admin/add-indicators` branch was working for me as of March 7. Not sure if this is user error or not.

**Comment by 9b** [comment]
Sorry about that! Forgot to add in the route alias in order to account for when the user does not specify an optional database node. It's now fixed.
