### ISSUE TITLE
Forward IP in case of proxy deployment

### ISSUE THREAD

**Issue by botherder** [blockadeio/cloud_node#3]
In case one deploys the API server for example with Nginx with proxy_pass, the IP address of the submitted will appear as 127.0.0.1.

```
{ "_id" : ObjectId("<SNIP>"), "url" : "<SNIP>", "ip" : "127.0.0.1", "time" : "2017-02-20T21:24:54.437Z", "userAgent" : "Mozilla/5.0 <SNIP>", "type" : "main_frame", "method" : "get", "match" : "<SNIP>" }
```

We need to pass on the forwarded IP from the proxy as the actual client IP.

**Comment by 9b** [comment]
I was hoping to avoid doing any client-side magic to reveal the IP address, but based on this configuration setup, I'd need to do that. I could add an endpoint to send back the user's original IP, but it would need to be outside of the proxy deployment. Thoughts?

**Comment by villain** [comment]
add a check in the api for the existence of a x-real-ip or x-forwarded-for in the header using flask.request:

request.headers['X-Forwarded-For']

**Comment by botherder** [comment]
Yes, I concur. That should be enough.

For a similar project, I had to do something like (mind, this is for Django):

```
    reporter_ip = request.META.get("REMOTE_ADDR")
    if not reporter_ip:
        reporter_ip = request.META.get("HTTP_X_REAL_IP")
    if not reporter_ip:
        reporter_ip = request.META.get("HTTP_X_FORWARDED_FOR")
```
